#include <algorithm>
#include <array>
#include <cassert>
#include <iostream>
#include <map>
#include <numeric>
#include <set>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

using Pt=std::array<int,3>;using Lab=std::pair<int,int>;
static int rk(Pt p){return p[0]+p[1]+p[2];}
static Lab ll(Pt p,int m){int i=std::min(p[1],m-p[0]),t=p[0]+p[1]-i,j=std::min(t,m-p[2]);return{i,j};}
static Lab rr(Pt p,int m){int i=std::min(p[2],m-p[0]),t=p[0]+p[2]-i,j=std::min(t,m-p[1]);return{i,j};}
struct Base {std::string name;std::vector<Pt>a;};
struct Piece {int base,lo,hi;};
struct Gap {int side,base,pos;auto operator<=>(const Gap&)const=default;};
struct Wit {int gen;Pt from,to;};
struct DG {std::vector<std::set<int>>g;std::map<std::pair<int,int>,Wit>w;std::vector<int>cy;};

static std::vector<Base> rawL(int m){std::map<Lab,std::vector<Pt>>f;for(int x=0;x<=m;x++)for(int y=0;y<=m;y++)for(int z=0;z<=m;z++){Pt p{x,y,z};f[ll(p,m)].push_back(p);}std::vector<Base>o;for(auto&[q,a]:f){std::sort(a.begin(),a.end(),[](Pt x,Pt y){return rk(x)<rk(y);});o.push_back({"L"+std::to_string(q.first)+","+std::to_string(q.second),a});}return o;}
static std::vector<Base> baseR(int m){std::map<Lab,std::vector<Pt>>r;for(int x=0;x<=m;x++)for(int y=0;y<=m;y++)for(int z=0;z<=m;z++){Pt p{x,y,z};r[rr(p,m)].push_back(p);}for(auto&[q,a]:r)std::sort(a.begin(),a.end(),[](Pt x,Pt y){return rk(x)<rk(y);});std::map<Lab,std::vector<Pt>>p,s;for(auto&[q,a]:r)if(q.first+q.second<=m){Pt u{q.second,q.first,q.first};for(Pt v:a)(rk(v)<=rk(u)?p[q]:s[q]).push_back(v);}std::set<Lab>up,us;std::vector<Base>o;for(int i=0;i<=m-2;i++)for(int j=0;j<=m-i-1;j++){auto a=p[{i,j}];a.insert(a.end(),s[{i+1,j}].begin(),s[{i+1,j}].end());o.push_back({"Q"+std::to_string(i)+","+std::to_string(j),a});up.insert({i,j});us.insert({i+1,j});}o.push_back({"B",r[{0,m}]});up.insert({0,m});us.insert({0,m});for(auto&[q,a]:r){int i=q.first,j=q.second;if(i+j<=m){if(!up.count(q)&&!p[q].empty())o.push_back({"P"+std::to_string(i)+","+std::to_string(j),p[q]});if(!us.count(q)&&!s[q].empty())o.push_back({"S"+std::to_string(i)+","+std::to_string(j),s[q]});}else o.push_back({"U"+std::to_string(i)+","+std::to_string(j),a});}return o;}
static std::vector<Piece> refine(const std::vector<Base>&b,const std::set<Gap>&cuts,int side){std::vector<Piece>o;for(int c=0;c<(int)b.size();c++){int lo=0;for(int z=0;z+1<(int)b[c].a.size();z++)if(cuts.count({side,c,z})){o.push_back({c,lo,z});lo=z+1;}o.push_back({c,lo,(int)b[c].a.size()-1});}return o;}
static int cyclic_metric(const std::vector<std::set<int>>&g){int n=g.size(),tm=0;std::vector<int>df(n,-1),lo(n),st;std::vector<char>on(n);int ti=0;auto dfs=[&](auto&&self,int u)->void{df[u]=lo[u]=ti++;st.push_back(u);on[u]=1;for(int v:g[u])if(df[v]<0){self(self,v);lo[u]=std::min(lo[u],lo[v]);}else if(on[v])lo[u]=std::min(lo[u],df[v]);if(lo[u]==df[u]){int z=0,v;do{v=st.back();st.pop_back();on[v]=0;z++;}while(v!=u);if(z>1)tm+=z*z;else if(g[u].count(u))tm++;}};for(int i=0;i<n;i++)if(df[i]<0)dfs(dfs,i);return tm;}
static void getcycle(DG&d){int n=d.g.size();std::vector<int>co(n),st;auto dfs=[&](auto&&self,int u)->bool{co[u]=1;st.push_back(u);for(int v:d.g[u]){if(!co[v]){if(self(self,v))return true;}else if(co[v]==1){auto it=std::find(st.begin(),st.end(),v);d.cy.assign(it,st.end());return true;}}st.pop_back();co[u]=2;return false;};for(int i=0;i<n&&!d.cy.size();i++)if(!co[i])dfs(dfs,i);}
struct State {DG pl,pr;std::vector<Piece>L,R;std::map<Pt,std::pair<int,int>> lp,rp;int metric;};
static State build(const std::vector<Base>&BL,const std::vector<Base>&BR,const std::set<Gap>&cuts){State s;s.L=refine(BL,cuts,0);s.R=refine(BR,cuts,1);for(int i=0;i<(int)s.L.size();i++)for(int z=s.L[i].lo;z<=s.L[i].hi;z++)s.lp[BL[s.L[i].base].a[z]]={i,z};for(int i=0;i<(int)s.R.size();i++)for(int z=s.R[i].lo;z<=s.R[i].hi;z++)s.rp[BR[s.R[i].base].a[z]]={i,z};s.pl.g.resize(s.L.size());s.pr.g.resize(s.R.size());
 // right order generated by left pieces
 for(int gi=0;gi<(int)s.L.size();gi++){auto&p=s.L[gi];int last=-1;Pt lp{};for(int z=p.lo;z<=p.hi;z++){Pt x=BL[p.base].a[z];int v=s.rp[x].first;if(last>=0&&last!=v){s.pr.g[last].insert(v);s.pr.w.try_emplace({last,v},Wit{gi,lp,x});}last=v;lp=x;}}
 // left order, reversed, generated by right pieces
 for(int gi=0;gi<(int)s.R.size();gi++){auto&p=s.R[gi];int last=-1;Pt lp{};for(int z=p.lo;z<=p.hi;z++){Pt x=BR[p.base].a[z];int v=s.lp[x].first;if(last>=0&&last!=v){s.pl.g[v].insert(last);s.pl.w.try_emplace({v,last},Wit{gi,x,lp});}last=v;lp=x;}}
 getcycle(s.pl);getcycle(s.pr);s.metric=cyclic_metric(s.pl.g)+cyclic_metric(s.pr.g);return s;}
static std::set<Gap> support(const State&s,const std::vector<Base>&BL,const std::vector<Base>&BR,bool leftcycle){const DG&d=leftcycle?s.pl:s.pr;const auto&target=leftcycle?s.L:s.R;const auto&gen=leftcycle?s.R:s.L;const auto&BT=leftcycle?BL:BR;const auto&BG=leftcycle?BR:BL;int ts=leftcycle?0:1,gs=1-ts;std::set<Gap>sup;int q=d.cy.size();std::vector<Pt>in(q),out(q);for(int z=0;z<q;z++){int u=d.cy[z],v=d.cy[(z+1)%q];auto w=d.w.at({u,v});out[z]=w.from;in[(z+1)%q]=w.to;auto gp=gen[w.gen];int a=(std::find(BG[gp.base].a.begin(),BG[gp.base].a.end(),w.from)-BG[gp.base].a.begin()),b=(std::find(BG[gp.base].a.begin(),BG[gp.base].a.end(),w.to)-BG[gp.base].a.begin());if(a>b)std::swap(a,b);for(int x=a;x<b;x++)sup.insert({gs,gp.base,x});}
 for(int z=0;z<q;z++){auto tp=target[d.cy[z]];int a=(std::find(BT[tp.base].a.begin(),BT[tp.base].a.end(),in[z])-BT[tp.base].a.begin()),b=(std::find(BT[tp.base].a.begin(),BT[tp.base].a.end(),out[z])-BT[tp.base].a.begin());if(a>b)std::swap(a,b);for(int x=a;x<b;x++)sup.insert({ts,tp.base,x});}return sup;}
int main(int argc,char**argv){int m=argc>1?std::stoi(argv[1]):4;auto BL=rawL(m),BR=baseR(m);std::set<Gap>cuts;State cur=build(BL,BR,cuts);while(cur.metric){std::set<Gap>cand;if(!cur.pl.cy.empty()){auto q=support(cur,BL,BR,true);cand.insert(q.begin(),q.end());}if(!cur.pr.cy.empty()){auto q=support(cur,BL,BR,false);cand.insert(q.begin(),q.end());}assert(!cand.empty());int best=1e9;Gap bg{};for(auto g:cand){auto cc=cuts;cc.insert(g);int z=build(BL,BR,cc).metric;if(z<best){best=z;bg=g;}}cuts.insert(bg);cur=build(BL,BR,cuts);std::cerr<<"cuts="<<cuts.size()<<" metric="<<cur.metric<<" chose "<<(bg.side?BR[bg.base].name:BL[bg.base].name)<<":"<<bg.pos<<"\n";}int cl=0,cr=0;for(auto g:cuts)(g.side?cr:cl)++;std::cout<<"m="<<m<<" W="<<BL.size()<<" baseR="<<BR.size()<<" cuts="<<cuts.size()<<" Lcuts="<<cl<<" Rcuts="<<cr<<"\n";for(auto g:cuts)std::cout<<(g.side?BR[g.base].name:BL[g.base].name)<<" "<<g.pos<<"\n";}
