#!/usr/bin/env python3
"""Finite checks for the exact configuration-leave interface.

This is not a nibble simulation.  It exhausts the bipartite cut criterion
through 3+3 vertices, the disjoint-block semigroup through nine resource
rows, the complete terminal residue intervals for q <= 64, and imports the
independent q=2 alternating-current certificate.
"""

from itertools import combinations, product

import verify_q2_near_c_alternating_lower_current as q2


def has_cut_condition(n, mask):
    def edge(i, j):
        return (mask >> (i * n + j)) & 1

    for xmask in range(1 << n):
        x = [i for i in range(n) if (xmask >> i) & 1]
        for ymask in range(1 << n):
            y_size = ymask.bit_count()
            crossing = sum(
                edge(i, j)
                for i in x
                for j in range(n)
                if not ((ymask >> j) & 1)
            )
            if crossing + 2 * y_size < 2 * len(x):
                return False
    return True


def has_simple_two_factor(n, mask):
    edges = [
        (i, j)
        for i in range(n)
        for j in range(n)
        if (mask >> (i * n + j)) & 1
    ]
    if len(edges) < 2 * n:
        return False
    for selected in combinations(edges, 2 * n):
        left = [0] * n
        right = [0] * n
        for i, j in selected:
            left[i] += 1
            right[j] += 1
        if left == [2] * n and right == [2] * n:
            return True
    return False


def audit_cut_criterion():
    counts = []
    for n in (1, 2, 3):
        count = 0
        for mask in range(1 << (n * n)):
            assert has_cut_condition(n, mask) == has_simple_two_factor(n, mask)
            count += 1
        counts.append((n, count))
    return counts


def audit_disjoint_blocks():
    blocks = ((0, 1), (2, 3, 4), (5, 6, 7, 8))
    columns = []
    for block in blocks:
        column = [0] * 9
        for row in block:
            column[row] = 1
        columns.append(tuple(column))

    semigroup = set()
    for choice in product((0, 1), repeat=len(blocks)):
        vector = tuple(
            sum(choice[j] * columns[j][row] for j in range(len(blocks)))
            for row in range(9)
        )
        semigroup.add(vector)

    for vector in product((0, 1), repeat=9):
        block_constant = all(len({vector[row] for row in block}) == 1 for block in blocks)
        assert (vector in semigroup) == block_constant

    # A partial block is separated by e_x-e_y and is outside even the
    # signed lattice generated by these disjoint whole-block columns.
    partial = (1, 0, 0, 0, 0, 0, 0, 0, 0)
    assert partial not in semigroup
    assert partial[0] - partial[1] == 1
    assert all(column[0] - column[1] == 0 for column in columns)
    return len(semigroup), 1 << 9


def audit_residue_intervals():
    checked = 0
    for q in range(2, 65):
        for bulk, minimum in ((2 * q + 1, 2 * q), (2 * q + 2, 2 * q + 2)):
            interval = range(minimum, minimum + bulk)
            residues = [m % bulk for m in interval]
            assert sorted(residues) == list(range(bulk))
            checked += bulk
    return checked


def audit_role_identity():
    # One explicit rail: common core {0,1}, q=3, six toggle labels.
    core = {0, 1}
    support = {2, 3, 4, 5, 6, 7}
    q = 3
    period = len(support)
    owner = {
        x: period * (x in core) + q * (x in support)
        for x in core | support
    }
    lower = {
        x: period * (x in core) + (q - 1) * (x in support)
        for x in core | support
    }
    reconstructed_support = {x: owner[x] - lower[x] for x in owner}
    reconstructed_core = {
        x: q * lower[x] - (q - 1) * owner[x]
        for x in owner
    }
    assert reconstructed_support == {x: int(x in support) for x in owner}
    assert reconstructed_core == {x: period * int(x in core) for x in owner}


def audit_q2_current():
    op, lp, up, kp = q2.decks(q2.PLUS)
    om, lm, um, km = q2.decks(q2.MINUS)
    assert q2.signed(op, om) == {(0, 1, 2): 1}
    current = q2.signed(lp, lm)
    assert current == q2.EXPECTED_LOWER_CURRENT
    assert sum(current.values()) == 1
    assert sum(abs(value) for value in current.values()) == 19
    assert q2.signed(up, um) == {0: -2, 4: 3, 5: -3, 7: 3}
    assert q2.signed(kp, km) == {0: 5, 1: 1, 2: 1, 4: -6, 5: 6, 7: -6}


def main():
    cut_counts = audit_cut_criterion()
    block_count, block_vectors = audit_disjoint_blocks()
    residue_count = audit_residue_intervals()
    audit_role_identity()
    audit_q2_current()
    print("cut_graphs", cut_counts)
    print("block_semigroup_vectors", block_count, "of", block_vectors)
    print("terminal_residues_checked", residue_count)
    print("role_identity", "PASS")
    print("q2_alternating_current", "PASS")
    print("PASS")


if __name__ == "__main__":
    main()
