#!/usr/bin/env python3
"""Pack strong GK-suffix-compatible FIFO paths in the middle layer.

Each candidate is a path of L=b distinct middle sources generated by one
ordered queue.  At every transition, the entire remaining GK addition
prefix agrees, so every source's retired chain is read correctly until its
top or the end of the path.  We solve the finite set-packing MILP exactly.
Exploratory; H100 only.
"""

from __future__ import annotations

from collections import Counter
from itertools import combinations, permutations
import sys
import numpy as np
from scipy.optimize import Bounds, LinearConstraint, milp
from scipy.sparse import coo_matrix


def additions(n: int, ones: frozenset[int]) -> tuple[int, ...]:
    bits = [int(i in ones) for i in range(n)]
    stack: list[int] = []
    matched = [False] * n
    for i, bit in enumerate(bits):
        if bit:
            stack.append(i)
        elif stack:
            j = stack.pop()
            matched[i] = matched[j] = True
    return tuple(reversed([i for i in range(n) if not matched[i] and not bits[i]]))


def candidates(b: int, L: int) -> tuple[list[frozenset[int]], int]:
    n = 2 * b
    sources = [frozenset(c) for c in combinations(range(n), b)]
    sid = {s: i for i, s in enumerate(sources)}
    add = {s: additions(n, s) for s in sources}

    def step(q: tuple[int, ...]) -> tuple[int, ...] | None:
        s = frozenset(q)
        aa = add[s]
        if not aa:
            return None
        qp = q[1:] + (aa[0],)
        ap = add[frozenset(qp)]
        if len(aa) == 1:
            return qp
        common = min(len(ap), len(aa) - 1)
        if common == 0 or ap[:common] != aa[1 : 1 + common]:
            return None
        return qp

    unique: set[frozenset[int]] = set()
    for q0 in permutations(range(n), b):
        q = q0
        path: list[int] = []
        seen: set[int] = set()
        for _ in range(L):
            z = sid[frozenset(q)]
            if z in seen:
                break
            seen.add(z)
            path.append(z)
            qp = step(q)
            if qp is None:
                break
            q = qp
        if len(path) == L:
            unique.add(frozenset(path))
    return list(unique), len(sources)


def solve(b: int, L: int) -> None:
    edges, N = candidates(b, L)
    rr: list[int] = []
    cc: list[int] = []
    for j, e in enumerate(edges):
        for v in e:
            rr.append(v)
            cc.append(j)
    A = coo_matrix((np.ones(len(rr)), (rr, cc)), shape=(N, len(edges))).tocsr()
    con = LinearConstraint(A, np.zeros(N), np.ones(N))
    res = milp(
        -np.full(len(edges), L, dtype=float),
        integrality=np.ones(len(edges)),
        bounds=Bounds(np.zeros(len(edges)), np.ones(len(edges))),
        constraints=con,
        options={"time_limit": 300.0, "mip_rel_gap": 0.0, "disp": False},
    )
    if res.x is None:
        raise RuntimeError(res.message)
    val = int(round(-res.fun))
    print(
        "CASE",
        b,
        "L",
        L,
        "N",
        N,
        "EDGES",
        len(edges),
        "COVER",
        val,
        "LEAVE",
        N - val,
        "FRACTION",
        val / N,
        "STATUS",
        res.message,
        flush=True,
    )


def stats(b: int, L: int) -> None:
    edges, N = candidates(b, L)
    deg = [0] * N
    codeg: Counter[tuple[int, int]] = Counter()
    for edge in edges:
        ee = sorted(edge)
        for u in ee:
            deg[u] += 1
        for i, u in enumerate(ee):
            for v in ee[i + 1 :]:
                codeg[(u, v)] += 1
    positive = [x for x in deg if x]
    print(
        "STATS",
        b,
        "L",
        L,
        "N",
        N,
        "EDGES",
        len(edges),
        "ZERO_DEG",
        sum(x == 0 for x in deg),
        "DEG_MIN_MAX_MEAN",
        min(positive, default=0),
        max(positive, default=0),
        sum(deg) / N,
        "DEG_HIST",
        sorted(Counter(deg).items())[:30],
        "CODEG_MAX",
        max(codeg.values(), default=0),
        "NORM_BY_MIN",
        max(codeg.values(), default=0) / min(positive, default=1),
        flush=True,
    )
def main() -> None:
    if len(sys.argv) >= 3:
        mode = sys.argv[1]
        b = int(sys.argv[2])
        if mode == "stats":
            stats(b, b)
        elif mode == "solve":
            solve(b, b)
        return
    for b in (3, 4, 5):
        stats(b, b)
        solve(b, b)


if __name__ == "__main__":
    main()
